title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal

title: <p align="center"> Shailesh Kadre </p>
logo: /assets/img/shailesh.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/shailesh-kadre-66266a28/">LinkedIn</a> |
  <a href="https://github.com/SHKADRE">GitHub</a>
  
  <br>   
20 plus years of experience in Engineering Analysis (FEA/ CAE), Project Management,
Product Design and Development in Aerospace, Railways, Automotive , Heavy Engineering 
and consumer products domain. 
PhD in Mechanical Engineering Design Optimization from College of Engineering Pune 
M. Tech. in Mechanical (Machine Dynamics) from Indian Institute of Technology, Kharagpur
B. E. in Mechanical from S.G.S.I.T.S, Indore

  <br>
  </p>



theme: jekyll-theme-minimal
